# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_auto_20180322_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(null=True),
        ),
    ]
