# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pwconfirm',
        ),
    ]
