# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
