# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 16:33
from __future__ import unicode_literals

import apps.login.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.login.models.validateLengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.login.models.validateLengthGreaterThanTwo]),
        ),
    ]
