# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
