# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0004_user_description'),
        ('comment_wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_from', to='log_reg.User'),
        ),
        migrations.AddField(
            model_name='wallmessage',
            name='user_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_for', to='log_reg.User'),
        ),
        migrations.AddField(
            model_name='wallmessage',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to='log_reg.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wall_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comment_wall.WallMessage'),
        ),
    ]
